

<div class = "row">
        
    <?php
        
        if ($this->sucesso == 1)
        { 
         ?>
        <script>
            alert("teste do ebola");
            location.href="<?=$this->url(array('controller'=>'alterar-senha','action'=>'index'),null,true)?>";
        </script>
            
        <?php
        }
        else 
        {   ?>
           <script>
                alert("Erro");
                history.go(-1);
            </script>
        <?php
        };
        ?>

</div>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br /><br />
<br />
<br />
<br /><br />
<br />
<br />
<br /><br />
<br />
<br />
<br /><br />
<br />
<br />
<br /><br />
<br />
<br />
<br /><br />
<br />
