<br/>
<br/>

<div class = "row">
        <div class = "small-6 columns  small-centered">
            <form data-abide method="post" action="<?=$this->url(array('controller'=>'alterar-senha','action'=>'consulta'),null,true)?>">
            <fieldset>
              <legend> E-mail </legend>
              <div class = "small-12 columns">
                <label>
                  <input type = "text" name = "tUserMail" id = "cUserMail"
                  placeholder = "Insira o e-mail de usuário..." required pattern = "[a-zA-Z]+"/>
                  <small class = "error"> Preencha o campo corretamente </small>
                </label>
              </div>
              
            </fieldset>
              
              <div class = "row">
            <!-- Botões: Entrar e Sair -->
              <div class = "small-7 columns">
              </div>

              <div class = "small-5 columns">
                <ul class = "button-group">
                    <li><input type="submit" class="button success small radius"/></li>
                  <li><a href="#" class="button alert small radius"> Voltar </a></li>
                </ul> 
              </div>
            </div>
              
        </form>
        
      </div>

</div>

<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
