<!DOCTYPE html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en" >

<head>
  <meta charset="utf-8">
  <!-- If you delete this meta tag World War Z will become a reality -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Epyon</title>

  <!-- If you are using the CSS version, only link these 2 files, you may add app.css to use for your overrides if you like -->
  <link rel="stylesheet" href="css/normalize.css">
  <link rel="stylesheet" href="css/foundation.css">

  <!-- If you are using the gem version, you need this only -->

  <script src="js/vendor/modernizr.js"></script>

</head>
<body>

<div class="row">
    <div class="fixed">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name"><h1><a href="<?=$this->url(array('controller'=>'index','action'=>'index'),null,true)?>">Epyon</a></h1></li>
          <li class="toggle-topbar menu-icon"><a href="">Menu</a></li>
        </ul>
        
        <section class="top-bar-section">
          <ul class="right">
            <li><a href="<?=$this->url(array('controller'=>'planos','action'=>'index'),null,true)?>">Planos</a></li>
            <li><a href="<?=$this->url(array('controller'=>'quem-somos','action'=>'index'),null,true)?>">Quem Somos</a></li>
            <li><a href="<?=$this->url(array('controller'=>'contato','action'=>'index'),null,true)?>">Contato</a></li>
            <li class="has-form"><a href="http://foundation.zurb.com/docs" class="button success radius">Entrar</a></li>
          </ul>
        </section>
      </nav>
    </div>
 </div>
    
    <div class="content">
        <?php echo $this->layout()->content;?>
    </div>

  <script src="js/vendor/jquery.js"></script>
  <script src="js/foundation.min.js"></script>
  <script>
    $(document).foundation();
  </script>
  
  <!-- Footer do layout principal -->
  <footer id="footer">
        <div class="row">
            <div class="small-3 columns small-centered">
               www.epyon.com.br © - 2014
            </div>
        </div>
        
        <div class="row">
            <div class="small-3 columns small-centered small-push-1">
                <strong><a href="<?=$this->url(array('controller'=>'index','action'=>'index'),null,true)?>">Epyon</a></strong>
            </div>
        </div>
  </footer>
  
</body>
</html>