<!DOCTYPE html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="pt-br" >

  <head>
    <meta charset="utf-8">
    <base href = "/epyonzf/public/"/>
    <!-- If you delete this meta tag World War Z will become a reality -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Inicial</title>

    <!-- If you are using the CSS version, only link these 2 files, you may add app.css to use for your overrides if you like -->
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/foundation.css">
    <link href="http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">

    <!-- If you are using the gem version, you need this only -->

    <script src="js/vendor/modernizr.js"></script>

  </head>

  <body>

    <div class="row">

      <div class="fixed">

        <nav class="top-bar" data-topbar>
          
          <ul class="title-area">
            
            <li class="name">
              
              <h1>
                
                <a href="<?=$this->url(array('controller'=>'index','action'=>'index'),null,true)?>">
                  <img src="img/epyon.png">
                </a>

              </h1>

            </li>
            
            <li class="toggle-topbar menu-icon"><a href="">Menu</a></li>

          </ul>
          
          <section class="top-bar-section">
            
            <ul class="right">
              
              <li>
                <a href="pag-home-pos-log.html">Home</a>
              </li>
              
              <li>
                <a href="pag-colaboradores.html"> Colaboradores </a>
              </li>

              <li>
                <a href="pag-projetos.html">Projetos</a> 
              </li>
              
              <li class = "has-dropdown">

                <a href="#">Relatórios</a>

                <ul class = "dropdown">

                  <li>
                    <a href="envio-relatorio.html">Enviar</a>
                  </li>

                  <li>
                    <a href="pag-relatorio.html">Visualizar</a>
                  </li>

                </ul>

              </li>
              
              <li>
                <a href="pag-estimativas.html">Estimativas</a>
              </li>
              
              <li>
                <a href="#"> Nome do Usuário </a>
              </li>

              <li class="has-form">
                <a href="<?=$this->url(array('controller'=>'autenticacao','action'=>'logout'),null,true)?>" class="button alert radius">Sair</a>
              </li>

            </ul>

          </section>

        </nav>
      
      </div>

    </div>
    
    <div class="content">
        <?php echo $this->layout()->content;?>
    </div>

    <!-- Footer do layout principal -->
    <footer id="footer">
          
          <div class="row">
            
            <div class = "small-12 columns">

              <fieldset>
                
                <div class="small-3 columns small-centered">
                   www.epyon.com.br © - 2014
                </div>

                <div class="small-3 columns small-centered small-push-1">
                    
                    <strong><a href="<?=$this->url(array('controller'=>'index','action'=>'index'),null,true)?>">Epyon</a></strong>

                </div>

              </fieldset>
            </div>

          </div>

    </footer>

    <script src="js/vendor/jquery.js"></script>
    <script src="js/foundation.min.js"></script>
    <script>
      $(document).foundation();
    </script>

    <script type="text/javascript">

      $(document).ready(function()
      {
        $("input#cDataNascimento").mask("99/99/9999");
      });

    </script>

  </body>


</html>