<!DOCTYPE html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="pt-br" >

  <head>
    <meta charset="utf-8">
    <base href = "/epyonzf/public/"/>
    <!-- If you delete this meta tag World War Z will become a reality -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Inicial</title>

    <!-- If you are using the CSS version, only link these 2 files, you may add app.css to use for your overrides if you like -->
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/foundation.css">
    <link href="http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">

    <!-- If you are using the gem version, you need this only -->

    <script src="js/vendor/modernizr.js"></script>

  </head>

  <body>

    <div class="row">

      <div class="fixed">

        <nav class="top-bar" data-topbar>
          
          <ul class="title-area">
            
            <li class="name">
              
              <h1>
                
                <a href="">
                  
                </a>

              </h1>

            </li>
            
            <li class="toggle-topbar menu-icon"><a href="">Menu</a></li>

          </ul>
          
          <section class="top-bar-section">
            
            <ul class="right">
              
              <li>
                <a href="<?=$this->url(array('controller'=>'pos-login','action'=>'index'),null,true)?>">Home</a>
              </li>
              
              <li>
                <a href="<?=$this->url(array('controller'=>'email-colaboradores','action'=>'index'),null,true)?>"> Colaboradores </a>
              </li>

              <li>
                <a href="<?=$this->url(array('controller'=>'projetos','action'=>'index'),null,true)?>">Projetos</a> 
              </li>
              
              <li class = "has-dropdown">

                <a>Relatórios</a>

                <ul class = "dropdown">

                  <li>
                    <a href="<?=$this->url(array('controller'=>'envio-relatorios','action'=>'index'),null,true)?>">Enviar</a>
                  </li>

                  <li>
                    <a href="<?=$this->url(array('controller'=>'relatorios','action'=>'index'),null,true)?>">Visualizar</a>
                  </li>

                </ul>

              </li>
              
              <li>
                <a href="<?=$this->url(array('controller'=>'estimativas','action'=>'index'),null,true)?>">Estimativas</a>
              </li>
              
              <li>
                <a href="#"> Nome do Usuário </a>
              </li>

              <li class="has-form">
                <a href="<?=$this->url(array('controller'=>'index','action'=>'index'),null,true)?>" class="button alert radius">Sair</a>
              </li>

            </ul>

          </section>

        </nav>
      
      </div>

    </div>
    
    <div class="content">
        <?php echo $this->layout()->content;?>
    </div>

    <!-- Footer do site -->
  
  <footer class="footer">
    <div class="row full-width">
        <div class="small-12 medium-3 large-4 columns">
            <i class="fi-laptop"></i>
            <p>O Epyon é um gerenciador de estimativas de desenvolvimento de software criado pela equipe da Versalius, com a finalidade de automatizar e gerenciar o processo de calculo de estimativas</p>
        </div>
      
    <div class="small-12 medium-3 large-4 columns">
        <i class="fi-shield"></i>
        <p>A segurança da informação é uma das maiores preocupações da nossa equipe, por isso desenvolvemos o Epyon visando proteger os dados dos nossos usuários.</p>
    </div>
    
    <div class="small-6 medium-3 large-2 columns">
      <h4>Menu</h4>
      <ul class="footer-links">
        <li><a href="<?=$this->url(array('controller'=>'index','action'=>'index'),null,true)?>">Home</a></li>
        <li><a href="<?=$this->url(array('controller'=>'planos','action'=>'index'),null,true)?>">Planos</a></li>
        <li><a href="<?=$this->url(array('controller'=>'quem-somos','action'=>'index'),null,true)?>">Quem Somos</a></li>
        <li><a href="<?=$this->url(array('controller'=>'contato','action'=>'index'),null,true)?>">Contato</a></li>
      <ul>
    </div>
    
    <div class="small-6 medium-3 large-2 columns">
      <h4>Siga-me</h4>
      <ul class="footer-links">
        <li><a href="#">Facebook</a></li>
        <li><a href="#">Twitter</a></li>
      <ul>
    </div>
  
  </div>
</footer>

    <script src="js/vendor/jquery.js"></script>
    <script src="js/foundation.min.js"></script>
    <script>
      $(document).foundation();
    </script>

    <script type="text/javascript">

      $(document).ready(function()
      {
        $("input#cDataNascimento").mask("99/99/9999");
      });

    </script>

  </body>


</html>