<br/>
    <div class="row">
        <div class="small-4 columns small-centered">
            <img src="img/logo-epyon/logo-site2.png">
        </div>
    </div>
    
    <div class="row">   
        <div class="small-12">
            <div class="path-container">
                <div class="row">
                    <div class="large-12 columns ">
                        <h1> Bem vindo ao Epyon!</h1>
                    </div>
                </div>
                
                <div class="row path-item">
                    <div class="large-7 push-5 columns">
                        <div class="circle circle-left "></div>
                    </div>
                    
                    <div class="large-5 pull-7 columns path-text left">
                        <h3>Seu gerenciador de estimativas de software</h3>
                        <p> Descrição </p>
                        <a href="#">saiba mais</a>
                    </div>         
                </div>
                
                <div class="row path-item">
                    <div class="large-7 columns">
                        <div class="circle circle-right right"></div>
                    </div>
                    <div class="large-5 columns path-text right">
                        <h3>Titulo 2</h3>
                        <p>Descrição</p>
                        <a href="#">Saiba mais</a>
                    </div>
                </div>
                
                <div class="row get-feedback path-item">
                    <div class="large-7 push-5 columns">
                        <div class="circle circle-left"></div>
                    </div>
                    <div class="large-5 pull-7 columns path-text left">
                        <h3>Titulo 3</h3>
                        <p> Descrição </p>
                        <a href="#">Saiba mais</a>
                    </div>
                </div>
  
                <div class="row land-job path-item">
                    <div class="large-7 columns">
                        <div class="circle circle-right right"></div>
                    </div>
                    <div class="large-5 columns path-text right">
                        <h3>Titulo 4 </h3>
                        <p> Descrição </p>
                        <a href="#">Saiba mais </a>
                    </div>
                </div>
                <span class="line hide-for-small"></span>
            </div>
        </div>        
    </div>
    