<br/>
    <div class="row">
        <div class="small-4 columns small-centered">
            <img src="img/logo-epyon/logo-site2.png">
        </div>
    </div>
    
    <div class="row">   
        <div class="small-12">
            <div class="path-container">
                <div class="row">
                    <div class="large-12 columns ">
                        <h1> Bem vindo ao Epyon!</h1>
                    </div>
                </div>
                
                <div class="row path-item">
                    <div class="large-7 push-5 columns">
                        <div class="circle circle-left "></div>
                    </div>
                    
                    <div class="large-5 pull-7 columns path-text left">
                        <h3>Seu gerenciador de estimativas de software</h3>
                        <p align="justify">
                           Se você procura uma ferramenta de gerenciamento de estimativas de software, o Epyon
                           é a melhor solução do mercado. Nosso sistema é de fácil utilização e fornece resultados de forma
                           clara e objetiva, aprimorando seu desempenho e aumentando a produtividade dos nossos clientes.
                        </p>
                        <a href="<?=$this->url(array('controller'=>'quem-somos','action'=>'index'),null,true)?>">saiba mais</a>
                    </div> 
                    
                </div>
                
                <div class="row path-item">
                    <div class="large-7 columns">
                        <div class="circle circle-right right"></div>
                    </div>
                    <div class="large-5 columns path-text right">
                        <h3>Contato</h3>
                        <p align="justify">
                           Caso necessite tirar alguma dúvida ou deseja saber mais sobre os trabalhos desenvolvidos pela
                           equipe da Versalius, contate-nos e ficaremos felizes em ajudá-lo. 
                        </p>
                        <a href="<?=$this->url(array('controller'=>'contato','action'=>'index'),null,true)?>">Saiba mais</a>
                    </div>
                </div>
                
                <div class="row get-feedback path-item">
                    <div class="large-7 push-5 columns">
                        <div class="circle circle-left"></div>
                    </div>
                    <div class="large-5 pull-7 columns path-text left">
                        <h3>Planos</h3>
                        <p align="justify"> 
                            Pensando em criar uma solução para seu problema, criamos planos diferenciados para cada tipo
                            de situação. Dessa forma acreditamos oferecer um melhor uso do nosso sistrma, de acordo com a sua
                            necessidade e com planos que cabem no seu bolso.
                        </p>
                        <a href="<?=$this->url(array('controller'=>'planos','action'=>'index'),null,true)?>">Saiba mais</a>
                    </div>
                </div>
  
                <div class="row land-job path-item">
                    <div class="large-7 columns">
                        <div class="circle circle-right right"></div>
                    </div>
                    <div class="large-5 columns path-text right">
                        <h3>Versalius </h3>
                        <p align="justify"> 
                            A versalius é uma equipe com profissionais altamente qualificados que se preocuparam em criar o
                            melhor ambiente para você, nosso futuro cliente. 
                        </p>
                        
                    </div>
                </div>
                <span class="line hide-for-small"></span>
            </div>
        </div>        
    </div>
    