

<div class = "row">
       
        <script>
            alert("O link não é válido!");
            location.href="<?=$this->url(array('controller'=>'index','action'=>'index'),null,true)?>";
        </script>
       
</div>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br /><br />
<br />
<br />
<br /><br />
<br />
<br />
<br /><br />
<br />
<br />
<br /><br />
<br />
<br />
<br /><br />
<br />
<br />
<br /><br />
<br />
