    <div class = "row">

        <div class = "small-10 columns small-centered">

            <form data-abide method="POST" action="<?=$this->url(array('controller'=>'nova-senha','action'=>'atualiza'),null,true)?>">
            
              <fieldset class = "panel radius" id = "fieldPadrao">
              
              <div class = "panel radius">

                <div class = "small-12 columns">

                  <h3> Alteração de Senha </h3>

                </div>
                
                <hr />

               </div>
              
              <div class = "small-12 columns">

                <label>

                  <b> Login </b>

                  <input type = "text" name = "tLogin" id = "cNomeColaborador"
                  placeholder = "Insira seu login..." required pattern="[a-zA-Z]"/>

                  <small class = "error"> Preencha o campo corretamente </small>

                </label>

              </div>    
              
              <div class = "small-12 columns">

                <label>

                  <b> Senha Atual </b>

                  <input type = "password" name = "tSenhaAtual" id = "cNomeColaborador"
                  placeholder = "Insira a senha atual..." required />

                  <small class = "error"> Preencha o campo corretamente </small>

                </label>

              </div>

              <div class = "small-12 columns">

                <label>

                  <b> Nova Senha </b>

                  <input type = "password" name = "tNovaSenha" id = "cEmailColaborador"
                  placeholder = "Insira nova senha..." required />

                  <small class = "error"> Preencha o campo corretamente </small>

                </label>

              </div>
                  
              <div class = "small-12 columns">

                <label>

                  <b> Repita Senha </b>

                  <input type = "password" name = "tRepitaSenha" id = "cEmailColaborador"
                  placeholder = "Repita a senha anterior..." required />

                  <small class = "error"> Preencha o campo corretamente </small>

                </label>

              </div>
                  
              <div class = "small-12 columns">

                  <input type = "hidden" name = "tSenha" value=""/>

                </label>

              </div>    
                  
              <div class = "small-12 columns">

                  <input type = "hidden" name = "tChave" value=""/>

                </label>

              </div> 

            </fieldset>
            
            <div class = "row">

            <!-- Botão Cancelar -->

            <div class = "small-10 columns">

              <a href="<?=$this->url(array('controller'=>'index','action'=>'index'),null,true)?>"
                 class = "button small large radius right"> Cancelar</a>

            </div>

            <!-- Botão Cadastrar -->

            <div class = "small-2 columns clearfix">

              <input type = "submit" id="btnCadastrar" class = "button success small large radius right" 
                     value = " Alterar " name = "Cadastrar"/> 

            </div>
                
          </form>

        </div>

       </div>

    </div>