<div class = "row">

      <div class = "small-10 columns small-centered">
      
        <form data-abide>

          <fieldset class = "panel radius" id = "fieldPadrao">

            <div class = "panel radius">

              <div class = "small-12 columns">

                <h3 id = "topo"> Envio de Relatórios </h3>

              </div>

              <hr />

            </div>

            <div class = "row">
              
              <div class = "small-12 columns">

                <label>

                  <b>Seu e-mail</b>

                  <input type = "text" name = "tNome" id = "cNome" placeholder = "Seu e-mail"
                  required pattern = "[a-zA-Z]+"/>

                  <small class = "error"> Preencha o campo corretamente </small>

                </label>

              </div>

            </div>

            <div class = "row">

              <div class = "small-12 columns">

                <label>

                  <b>E-mails dos Colaboradores</b>

                </label>

                <table class = "small-12 columns">

                    <thead>

                      <tr>

                        <th> Nome </th>
                        <th> E-mail </th>
                        <th> Selecionar </th>

                      </tr>

                    </thead>

                    <tbody id = "email_col">

                        <?php
                            if ($this->dadosColaborador != null)
                            {
                                foreach ($this->dadosColaborador as $tupla)
                                { ?>

                                    <tr scope = "row">

                                        <td scope = "column"> <?php echo $tupla['nomeCompleto'] ?> </td>
                                        <td scope = "column"> <?php echo $tupla['email'] ?> </td>
                                        <td scope = "column"> <input type = "checkbox" name = "check_email" value="email"/> </td>
                                        
                                    </tr><?php

                                }
                            }
                        ?>

                    </tbody>

                  </table>

              </div>

            </div>
            
            <div class ="row">
            
                <div class = "small-12 columns">
                    <label>

                      <b> Corpo do E-mail </b>

                      <textarea name = "corpo_email" placeholder = "Corpo do e-mail" id = "cTxtAreaProj"></textarea>

                    </label>

                    <label>

                      <b>Relatórios Cadastrados </b>

                    </label>

                    <table class = "small-12 columns">

                      <thead>

                        <tr>

                          <th> Nome </th>
                          <th> Selecionar </th>

                        </tr>

                      </thead>

                      <tbody id = "check_relatorios">

                          <?php
                                if ($this->dadosRelatorio != null)
                                {
                                    foreach ($this->dadosRelatorio as $tupla)
                                    { ?>

                                        <tr scope = "row">

                                            <td scope = "column"> <?php echo $tupla['nome'] ?> </td>
                                            <td scope = "column"> <input type = "checkbox" name = "check_email" value="email"/> </td>

                                        </tr><?php

                                    }
                                    foreach ($this->dadosRelatorioBd as $tupla)
                                    { ?>

                                        <tr scope = "row">

                                            <td scope = "column"> <?php echo $tupla['nome'] ?> </td>
                                            <td scope = "column"> <input type = "checkbox" name = "check_email" value="email"/> </td>

                                        </tr><?php

                                    }
                                }
                            ?>

                      </tbody>

                    </table>
                </div>
            </div>
          </fieldset>

          <!-- Botões -->

        <div class = "row">

          <!-- Botão Cancelar -->

            <div class = "small-10 columns">

              <a href="<?= $this->url(array('controller'=>'relatorios', 'action'=>'index')) ?>" class = "button small large radius right"> Cancelar</a>

            </div>

            <!-- Botão Cadastrar -->

            <div class = "small-2 columns clearfix">

              <a href="<?= $this->url(array('controller'=>'projetos', 'action'=>'index'))?>" class = "button success small large-12 radius right"> Enviar </a>

            </div>
          
        </div>

        </form>

      </div>

    </div>