<div class = "row">

      <div class = "small-10 columns small-centered">
      
        <form data-abide>

          <fieldset class = "panel radius" id = "fieldPadrao">

            <div class = "panel radius">

              <div class = "small-12 columns">

                <h3 id = "topo"> Envio de Relatórios </h3>

              </div>

              <hr />

            </div>

            <div class = "row">
              
              <div class = "small-12 columns">

                <label>

                  <b>Seu e-mail</b>

                  <input type = "text" name = "tNome" id = "cNome" placeholder = "Seu e-mail"
                  required pattern = "[a-zA-Z]+"/>

                  <small class = "error"> Preencha o campo corretamente </small>

                </label>

              </div>

            </div>

            <div class = "row">

              <div class = "small-12 columns">

                <label>

                  <b>E-mails dos Colaboradores</b>

                </label>

                <table>

                    <thead>

                      <tr>

                        <th> Nome </th>
                        <th> E-mail </th>
                        <th> Selecionar </th>

                      </tr>

                    </thead>

                    <tbody>

                      <tr>

                        <td> Cleiton Fernando </td>
                        <td> cflsena2@gmail.com</td>
                        <td> <input type = "checkbox" name = "tSelecionar1" id = "cProjeto1"/></td>

                      </tr>

                      <tr>

                        <td> Luiza Miranda </td>
                        <td> luiza@gmail.com</td>
                        <td> <input type = "checkbox" name = "tSelecionar3" id = "cProjeto2"/></td>

                      </tr>

                      <tr>

                        <td> Alessandro Barbieri</td>
                        <td> alessandrobarbieri@gmail.com</td>
                        <td> <input type = "checkbox" name = "tSelecionar3" id = "cProjeto3"/></td>

                      </tr>

                      <tr>

                        <td> Marcos Lopes </td>
                        <td> marcoslopes@gmail.com</td>
                        <td> <input type = "checkbox" name = "tSelecionar4" id = "cProjeto4"/></td>

                      </tr>

                    </tbody>

                  </table>

              </div>

            </div>

            <label>

              <b> Corpo do E-mail </b>

              <textarea placeholder = "Corpo do e-mail" id = "cTxtAreaProj"></textarea>

            </label>

            <label>

              <b>Relatórios Cadastrados </b>

            </label>

            <table>

              <thead>

                <tr>

                  <th> Nome </th>
                  <th> Selecionar </th>

                </tr>

              </thead>

              <tbody>

                <tr>

                  <td> Controle de Estoque </td>
                  <td> <input type = "checkbox" name = "tSelecionar1" id = "cRelatorio1"/></td>

                </tr>

                <tr>

                  <td> Locadora de Veículos </td>
                  <td> <input type = "checkbox" name = "tSelecionar3" id = "cRelatorio2"/></td>

                </tr>

                <tr>

                  <td> Sistema de Automação Residencial </td>
                  <td> <input type = "checkbox" name = "tSelecionar3" id = "cRelatorio3"/></td>

                </tr>

                <tr>

                  <td> Sistema de Notas </td>
                  <td> <input type = "checkbox" name = "tSelecionar4" id = "cRelatorio4"/></td>

                </tr>

              </tbody>

            </table>

          </fieldset>

          <!-- Botões -->

        <div class = "row">

          <!-- Botão Cancelar -->

            <div class = "small-10 columns">

              <a href="<?= $this->url(array('controller'=>'projetos', 'action'=>'index')) ?>" class = "button alert small large radius right"> Cancelar</a>

            </div>

            <!-- Botão Cadastrar -->

            <div class = "small-2 columns clearfix">

              <a href="<?= $this->url(array('controller'=>'projetos', 'action'=>'index'))?>" class = "button success small large-12 radius right"> Enviar </a>

            </div>
          
        </div>

        </form>

      </div>

    </div>