<div class = "row">

      <div class = "small-6 columns small-centered small-push-1">

        <h3> Cadastro de Colaboradores </h3>

      </div>

    </div>

    <div class = "row">

        <div class = "small-10 columns small-centered">

          <form data-abide>
            <fieldset>
              
              <legend> E-mail do Colaborador </legend>

              <div class = "small-12 columns">

                <label>

                  <b>Nome do Colaborador </b>

                  <input type = "text" name = "tNomeColaborador" id = "cNomeColaborador"
                  placeholder = "Insira o nome do colaborador..." required pattern = "[a-zA-Z]+"/>

                  <small class = "error"> Preencha o campo corretamente </small>

                </label>

              </div>

              <div class = "small-12 columns">

                <label>

                  <b> E-mail </b>

                  <input type = "text" name = "tEmailColaborador" id = "cEmailColaborador"
                  placeholder = "Insira o e-mail do colaborador" required pattern = "[a-zA-Z]+"/>

                  <small class = "error"> Preencha o campo corretamente </small>

                </label>

              </div>

            </fieldset>

          </form>

          <div class = "row">

          <!-- Botão Cancelar -->

            <div class = "small-10 columns">

              <a href="#" class = "button alert small large radius right"> Cancelar</a>

            </div>

            <!-- Botão Cadastrar -->

            <div class = "small-2 columns clearfix">

              <a href="#" class = "button success small large radius right"> Cadastrar</a>

            </div>
          
        </div>

       </div>

    </div>