    <div class = "row">

        <div class = "small-10 columns small-centered">

            <form data-abide method="POST" action="<?=$this->url(array('controller'=>'cadastro-colaboradores','action'=>'update'),null,true)?>">
            
              <fieldset class = "panel radius" id = "fieldPadrao">
              
              <div class = "panel radius">

                <div class = "small-12 columns">

                  <h3> Cadastro de Colaboradores </h3>

                </div>
                
                <hr />

               </div>

              <div class = "small-12 columns">

                <label>

                  <b>Nome do Colaborador </b>

                  <input type = "text" name = "tNomeColaborador" value="<?=$this->dados[0]['nomeCompleto']?>" id = "cNomeColaborador"
                  placeholder = "Insira o nome do colaborador..." required pattern = "[a-zA-Z]+" />

                  <small class = "error"> Preencha o campo corretamente </small>

                </label>

              </div>

              <div class = "small-12 columns">

                <label>

                  <b> E-mail </b>

                  <input type = "text" name = "tEmailColaborador" value="<?=$this->dados[0]['email']?>" id = "cEmailColaborador"
                  placeholder = "Insira o e-mail do colaborador" required pattern = "[a-zA-Z]+"/>

                  <small class = "error"> Preencha o campo corretamente </small>

                </label>

              </div>

            </fieldset>
            
            <div class = "row">

            <!-- Botão Cancelar -->

            <div class = "small-10 columns">

              <a href="<?=$this->url(array('controller'=>'email-colaboradores','action'=>'index'),null,true)?>"
                 class = "button alert small large radius right"> Cancelar</a>

            </div>

            <!-- Botão Cadastrar -->

            <div class = "small-2 columns clearfix">

              <input type = "submit" id="btnCadastrar" class = "button success small large radius right" 
                     value = "Cadastrar" name = "Cadastrar"/> 

            </div>
            
            <div>
                <input type="hidden" id="btnHidden" value ="<?= $this->idColGet ?>" name="tHiddenCol" />
            </div>
                
          </form>

        </div>

       </div>

    </div>