<div class = "row">

      <div class = "small-10 columns small-centered">
      
      <fieldset class = "panel radius" id = "fieldPadrao">

          <div class = "small-10 columns small-centered panel radius">

            <div class = "small-12 columns">

              <h3 id = "topo"> Relatórios </h3>

            </div>

            <hr />

          </div><br>

          <table class = "small-10 columns small-centered">

            <caption> Tabela de Relatórios </caption>
            
            <thead>
              
              <tr scope = "row">
                
                <th scope = "column"> Projeto </th>
                <th scope = "column"> Relatório </th>
                <th scope = "column"> Download </th>

              </tr>

            </thead>
          
            <tbody>
            
                <?php
                    if ($this->dados != null)
                    {
                        foreach ($this->dados as $tupla)
                        { ?>
                            
                            <tr scope = "row">

                                <td scope = "column"> <?php echo $tupla['nome'] ?> </td>
                                <td scope = "column"> <?php echo '<a href = "'.$this->url(array('controller'=>'relatorios','action'=>'pdf','idProjeto'=>$tupla['idProjetos'],'opcao'=>0),null,true).'" target="_blank"> <i class = "fi-page" id = "iConGeral"></i></a>';?></td>
                                <td scope = "column"> <?php echo '<a href = "'.$this->url(array('controller'=>'relatorios','action'=>'pdf','idProjeto'=>$tupla['idProjetos'],'opcao'=>1),null,true).'"> <i class = "fi-download" id = "iConGeral"></i></a>';?></td>

                            </tr><?php

                        }
                        
                        foreach ($this->dados2 as $tupla)
                        { ?>
                            
                            <tr scope = "row">

                                <td scope = "column"> <?php echo $tupla['nome'] ?> </td>
                                <td scope = "column"> <?php echo '<a href = "'.$this->url(array('controller'=>'relatorios','action'=>'pdfbd','idProjeto'=>$tupla['idProjetoBd'],'opcao'=>0),null,true).'" target="_blank"> <i class = "fi-page" id = "iConGeral"></i></a>';?></td>
                                <td scope = "column"> <?php echo '<a href = "'.$this->url(array('controller'=>'relatorios','action'=>'pdfbd','idProjeto'=>$tupla['idProjetoBd'],'opcao'=>1),null,true).'"> <i class = "fi-download" id = "iConGeral"></i></a>';?></td>

                            </tr><?php

                        }
                    }
                ?>

            </tbody>  

          </table>

        </fieldset>

      </div>

    </div>