<div class = "row">

      <div class = "small-10 columns small-centered">
      
      <fieldset class = "panel radius" id = "fieldPadrao">

          <div class = "small-10 columns small-centered panel radius">

            <div class = "small-12 columns">

              <h3 id = "topo"> Relatórios </h3>

            </div>

            <hr />

          </div><br>

          <table class = "small-10 columns small-centered">

            <caption> Tabela de Relatórios </caption>
            
            <thead>
              
              <tr scope = "row">
                
                <th scope = "column"> Projeto </th>
                <th scope = "column"> Editar </th>
                <th scope = "column"> Excluir </th>

              </tr>

            </thead>
          
            <tbody>
            
                <tr scope = "row">
                  
                  <td scope = "row"> Engenharia de Software </td>
                  <td scope = "row"> <a> <i class = "fi-pencil" id = "iConGeral"></i></a> </td>
                  <td scope = "row"> <a> <i class = "fi-x-circle" id = "iConGeral"></i></a> </td>

                </tr>

                <tr scope = "row">
                  
                  <td scope = "row"> Programação Web </td>
                  <td scope = "row"> <a> <i class = "fi-pencil" id = "iConGeral"></i></a> </td>
                  <td scope = "row"> <a> <i class = "fi-x-circle" id = "iConGeral"></i></a> </td>

                </tr>

            </tbody>  

          </table>

        </fieldset>

      </div>

    </div>