<br />
    <div class="row">
        <div class="small-12 columns small-centered">
            <img src="img/logo-versalius/logo-versalius.png">
        </div>
    </div>

    <div class = "row">
        <div class = "small-12 columns small-centered">
          <form data-abide>
            <fieldset>
              <div class = "small-12 columns">
                <label>
                    <td> <div align="justify"> <h6>Em 2014 um projeto ambicioso surgiu, este tinha como objetivo juntar uma equipe de desenvolvedores experientes para criar uma Software House que pudesse gerar soluções para um conjunto de diversos problemas. Nossa equipe conta com profissionais com experiência em desenvolvimento de software, infraestrutura de sistemas e segurança da informação. Todas essas caractéristicas juntas são fundamentais para o que se espera entregar a você, nosso futuro cliente, uma solução de qualidade.</h6></div> </td>
                </label>
              </div>
            </fieldset>
          </form>
        </div>
    </div>
    
    <div class="row">
        <div class="small-3 columns small-centered">
            <img src="img/logo-epyon/logo-site2.png">
        </div>
    </div>

    <div class = "row">
        <div class = "small-12 columns small-centered">
          <form data-abide>
            <fieldset>
              <legend> O que é o Epyon? </legend>
              <div class = "small-12 columns">
                <label>
                    <td> <div align="justify"> <h6>O Epyon é um software para Gestão de Estomativas de Software com funcionamento 100% web. Ele veio para suprir as necessidades de pessoas e empresas no controle diário das estimativas de projetos, atividade que visa otimizar os procedimentos e aumentar a produtividade da empresa.
                                             <br><br>Com acesso via web a solução permite organizar atividades pessoais e profissionais, criar e gerenciar estimativas, compartilhar resultados com sua equipe entre outras funcionalidades.</h6></div> </td>
                </label>
              </div>
            </fieldset>
          </form>
        </div>
    </div>

    <div class = "row">
        <div class = "small-12 columns small-centered">
          <form data-abide>
            <fieldset>
              <legend> Nossos Usuários </legend>
              <div class = "small-12 columns">
                <label>
                    <td> <div align="justify"> <h6>Procuramos construir soluções para os mais diversos tipos de usuários. Desse modo, não nos limitamos em fazer software para um público selecionado. Nosso principal objetivo é criar um conjunto de soluções que se adequem ao perfil de cada cliente.</h6></div> </td>
                </label>
              </div>
            </fieldset>
          </form>
        </div>
    </div>