<div class = "row">

      <div class = "small-12 columns small-centered">
      
      <fieldset class = "panel radius" id = "fieldPadrao">

        <div class = "small-12 columns small-centered panel radius">

          <div class = "small-12 columns">

            <h3 id = "topo"> Estimativas </h3>

          </div>

          <hr />

        </div><br>

          <table class = "small-10 columns small-centered">

            <caption> Tabela de Estimativas </caption>
            
            <thead>
              
              <tr scope = "row">
                
                <th scope = "column"> Projeto </th>
                <th scope = "column"> Custo </th>
                <th scope = "column"> Tempo </th>
                <th scope = "column"> Esforço </th>
                <th scope = "column"> Tipo de Métrica </th>

              </tr>

            </thead>
          
            <tbody>
            
                <?php
                    if ($this->dados != null)
                    { $flag = 0;$flag1 = 0;
                        foreach ($this->dados as $tupla)
                        { ?>

                            <tr scope = "row">

                                <td scope = "column"> <?php echo $tupla[$flag]['nome'] ?> </td>
                                <td scope = "column"> <?php echo '$ '.$tupla[$flag]['custo'] ?> </td>
                                <td scope = "column"> <?php echo 'HC '.$tupla[$flag]['tempo'] ?> </td>
                                <td scope = "column"> <?php echo 'H/P '.$tupla[$flag]['esforco'] ?> </td>
                                <td scope = "column"> <?php echo $tupla[$flag]['tipo_metrica'] ?></td>

                            </tr><?php
                            $flag++;
                        }
                        foreach ($this->dados2 as $tupla)
                        { ?>
                            
                            <tr scope = "row">

                                <td scope = "column"> <?php echo $tupla[$flag1]['nome'] ?> </td>
                                <td scope = "column"> <?php echo $tupla[$flag1]['custo'] ?> </td>
                                <td scope = "column"> <?php echo $tupla[$flag1]['tempo'] ?> </td>
                                <td scope = "column"> <?php echo $tupla[$flag1]['esforco'] ?> </td>
                                <td scope = "column"> <?php echo $tupla[$flag1]['tipo_metrica'] ?></td>

                            </tr><?php
                            $flag1++;
                        }
                    }
                ?>

            </tbody>  

          </table>

        </fieldset>
          
          <div>
              <fieldset class = "panel radius" id = "fieldPadrao">
                  <div class="row">
                      
                  
                    <div class="small-10 columns">
                        <p>
                            <b>Legenda: </b> 
                        </p>
                        <p align="justify">
                            <b>FPU</b>: são os dados fornecidos pelo usuário
                            na utilização da métrica de estimativa com base em um banco de dados
                            histórico.
                        </p>
                        
                        <p align="justify">
                            <b>BD</b>: Métrica com base em um banco de dados histórico.
                        </p>
                        
                        <p align="justify">
                            <b>AS</b>: Métrica denominada autossuficiente, com base em uma série de dados
                                       fornecidos pelo usuário.
                        </p>
                        
                        <p align="justify">
                            <b>HC</b>: Quantidade de horas corridas do presente projeto.
                        </p>
                        
                        <p align="justify">
                            <b>H/P</b>: Esforço de cada membro da equipe em hora.
                        </p>
                    </div>
                  
                  </div>
              </fieldset>
          </div>

      </div>

    </div>