<div class = "row">

      <div class = "small-10 columns small-centered">
      
      <fieldset class = "panel radius" id = "fieldPadrao">

        <div class = "small-10 columns small-centered panel radius">

          <div class = "small-12 columns">

            <h3 id = "topo"> Estimativas </h3>

          </div>

          <hr />

        </div><br>

          <table class = "small-10 columns small-centered">

            <caption> Tabela de Estimativas </caption>
            
            <thead>
              
              <tr scope = "row">
                
                <th scope = "column"> Projeto </th>
                <th scope = "column"> Custo </th>
                <th scope = "column"> Tempo </th>
                <th scope = "column"> Esforço </th>
                <th scope = "column"> Excluir </th>

              </tr>

            </thead>
          
            <tbody>
            
                <?php
                    if ($this->dados != null)
                    {
                        foreach ($this->dados as $tupla)
                        { ?>

                            <tr scope = "row">

                                <td scope = "column"> <?php echo $tupla['nome'] ?> </td>
                                <td scope = "column"> <?php echo $tupla['custo'] ?> </td>
                                <td scope = "column"> <?php echo $tupla['tempo'] ?> </td>
                                <td scope = "column"> <?php echo $tupla['esforco'] ?> </td>
                                <td scope = "column"> <?php echo '<a href = "'.$this->url(array('controller'=>'cadastro-colaboradores','action'=>'delete','idEst'=>$tupla['idEstimativas']),null,true).'"> <i class = "fi-x-circle" id = "iConGeral"></i></a>';?></td>

                            </tr><?php

                        }
                    }
                ?>

            </tbody>  

          </table>

        </fieldset>

      </div>

    </div>