<br/>
<br/>
<div class = "row">

    <div class = "small-10 columns small-centered">

        <div class="row step-by-step-style-one">
            <fieldset>
                <div class = "small-12 columns panel">

                    <h4> Bem-vindo, <?= $this->name_user . '!'; ?> </h4>
                    <hr/>
                </div>
                <p align = "justify">
                    Este é o seu sistema de gerenciamento de estimativas no processo
                    de desenvolvimento de <i>softwares</i>. Com esta ferramenta você
                    terá a possibilidade de otimizar seu trabalho e tudo de maneira
                    muito simples e rápida, de fácil utilização e acesso. Bom uso!
                </p>
            </fieldset>

        </div>


        <div  class="row step-by-step-style-two">
            <fieldset>

                <div class="small-12 columns panel">
                    <h4>Mini-Tutorial</h4>
                    <hr>
                </div>

                <div  class="small-12 large-4 columns">

                    <div class="path-item">
                        <div class="circlenumber">
                            <h3>1</h3>
                        </div>
                        <p align="justify">
                            Ao clicar no ícone <img src="img/icon_mais.png" alt="icone_mais" />, tanto de colaboradores,
                            quanto de projetos, você será direcionado para uma página de cadastro referente a aba que está navegando. 
                            Nessa página, encontram-se todos os campos necessários para fazer o cadastramento do item em questão.
                        </p>
                    </div>
                </div>
                <div  class="small-12 large-4 columns">
                    <div class="path-item">
                        <div class="circlenumber">
                            <h3>2</h3>
                        </div>
                        <p align="justify">
                            Assim como no tutorial 1, ao clicar no ícone <img src="img/icon_editar.png" alt="icone_editar" />, 
                            tanto de colaboradores, quanto de projetos, você será direcionado para uma página, referente 
                            a aba que está navegando, que será possível editar as informações que deseja.
                        </p>
                    </div>
                </div>
                <div  class="small-12 large-4 columns">
                    <div class="path-item">
                        <div class="circlenumber">
                            <h3>3</h3>
                        </div>
                        <p align="justify">
                            Ao clicar no ícone <img src="img/icon_rel_view.png" alt="icone_relatorio_view" />
                            você será direcionado para outra aba que conterá um relatório gerado pelo sistema Epyon,
                            referente ao projeto que deseja. Nessa nova aba, se você quiser, poderá salvar o relatório
                            em formato pdf. Caso precise que esse processo seja ainda mais rápido, clicando no ícone 
                            <img src="img/icon_rel_down.png" alt="icone_relatorio_down" /> seu relatório será baixado
                            automaticamente em seu dispositivo.
                        </p>
                    </div>
                </div>
                
                <div>
                
                    
                    
                </div>
                
            </fieldset>


        </div>

    </div>