<div class = "row">

      <div class = "small-10 columns small-centered">

        <fieldset  id = "fieldPadrao" class = "panel radius">

          <div class = "panel radius">

            <div class = "small-12 columns">

              <h4> Bem-vindo, <?= $this->name_user.'!'; ?> </h4>

            </div>

            <hr />

          </div>

          <div class = "small-12 columns">

            <p>Irei inserir um texto informativo</p>

          </div>

        </fieldset>

        <fieldset id = "fieldPadrao" class = "panel radius">

          <div class = "panel radius">
            
            <div class = "small-12 columns">
              
              <h4> Tutorial </h4>

            </div>

            <hr />

          </div>

          <div class = "row">
            
            <div class = "small-12 columns">
              
              <p> Irei inserir um tutorial aqui </p>

            </div>

          </div>

        </fieldset>

      </div>

    </div>