<div class = "row">

      <div class = "small-10 columns small-centered">
      
      <fieldset class = "panel radius" id = "fieldPadrao">

          <div class ="small-10 columns small-centered panel radius">

            <div class = "small-11 columns">

              <h3 id = "topo"> Projetos </h3>

            </div>

            <div class = "small-1 columns">
              <a href="<?=$this->url(array('controller'=>'cadastro-projetos','action'=>'index'),null,true)?>"><i class = "fi-plus" id = "iConGeral"></i></a>
            </div>

            <hr />

        </div><br>

          <table class = "small-10 columns small-centered">

            <caption> Tabela de Projetos </caption>
            
            <thead>
              
              <tr scope = "row">
                
                <th scope = "column"> Projeto </th>
                <th scope = "column"> Tipo Projeto </th>
                <th scope = "column"> Editar </th>
                <th scope = "column"> Excluir </th>

              </tr>

            </thead>
          
            <tbody>
            
                <?php
                    if ($this->dados != null)
                    {
                        foreach ($this->dados as $tupla)
                        { ?>

                            <tr scope = "row">

                                <td scope = "column"> <?php echo $tupla['nome'] ?> </td>
                                <td scope = "column"> <?php echo $tupla['tipo_projeto'] ?> </td>
                                <td scope = "column"> <?php echo '<a href = "'.$this->url(array('controller'=>'cadastro-projetos','action'=>'recupera','idProjeto'=>$tupla['idProjetos']),null,true).'"> <i class = "fi-pencil" id = "iConGeral"></i></a>';?></td>
                                <td scope = "column"> <?php echo '<a href = "'.$this->url(array('controller'=>'cadastro-projetos','action'=>'delete','idProjeto'=>$tupla['idProjetos']),null,true).'"> <i class = "fi-x-circle" id = "iConGeral"></i></a>';?></td>

                            </tr><?php

                        }
                        foreach ($this->dados2 as $tupla)
                        { ?>

                            <tr scope = "row">

                                <td scope = "column"> <?php echo $tupla['nome'] ?> </td>
                                <td scope = "column"> <?php echo $tupla['tipo_projeto'] ?> </td>
                                <td scope = "column"> <?php echo '<a href = "'.$this->url(array('controller'=>'cadastro-projetos','action'=>'recuperabd','idProjeto'=>$tupla['idProjetoBd']),null,true).'"> <i class = "fi-pencil" id = "iConGeral"></i></a>';?></td>
                                <td scope = "column"> <?php echo '<a href = "'.$this->url(array('controller'=>'cadastro-projetos','action'=>'deletebd','idProjeto'=>$tupla['idProjetoBd']),null,true).'"> <i class = "fi-x-circle" id = "iConGeral"></i></a>';?></td>

                            </tr><?php

                        }
                    }
                ?>

            </tbody>  

          </table>
        
        </fieldset>

      </div>

    </div>