<div class = "row">

      <div class = "small-10 columns small-centered">
      
      <fieldset class = "panel radius" id = "fieldPadrao">

          <div class ="small-10 columns small-centered panel radius">

            <div class = "small-11 columns">

              <h3 id = "topo"> Projetos </h3>

            </div>

            <div class = "small-1 columns">
              <a href="<?=$this->url(array('controller'=>'cadastro-projetos','action'=>'index'),null,true)?>"><i class = "fi-plus" id = "iConGeral"></i></a>
            </div>

            <hr />

        </div><br>

          <table class = "small-10 columns small-centered">

            <caption> Tabela de Projetos </caption>
            
            <thead>
              
              <tr scope = "row">
                
                <th scope = "column"> Projeto </th>
                <th scope = "column"> Estimativas </th>
                <th scope = "column"> Editar </th>
                <th scope = "column"> Excluir </th>

              </tr>

            </thead>
          
            <tbody>
            
                <tr scope = "row">
                  
                  <td scope = "row"> Controle de Estoque </td>
                  <td scope = "row"> <a href="pag-estimativas.html"> <i class="fi-results" id = "iConGeral"></i></a> </td>
                  <td scope = "row"> <a> <i class = "fi-pencil" id = "iConGeral"></i></a> </td>
                  <td scope = "row"> <a> <i class = "fi-x-circle" id = "iConGeral"></i></a> </td>

                </tr>

                <tr scope = "row">
                  
                  <td scope = "row"> Locadora de Veículos </td>
                  <td scope = "row"> <a href="pag-estimativas.html"> <i class="fi-results" id = "iConGeral"></i></a> </td>
                  <td scope = "row"> <a> <i class = "fi-pencil" id = "iConGeral"></i></a> </td>
                  <td scope = "row"> <a> <i class = "fi-x-circle" id = "iConGeral"></i></a> </td>

                </tr>

            </tbody>  

          </table>

        </fieldset>

      </div>

    </div>